FROM node:17-alpine

WORKDIR usr/src/app

ENV NODE_ENV=development

COPY package*.json ./

RUN yarn global add @nestjs/cli

RUN yarn install

ENV NODE_ENV=development

COPY . .

EXPOSE 3000

CMD ["yarn", "run", "start:dev"]